[build]
  publish = "public"
  command = "rm -rf themes/congo && git clone https://github.com/jpanther/congo.git themes/congo && cp -r themes/congo/layouts/_partials themes/congo/layouts/partials && cp -r themes/congo/layouts/_shortcodes themes/congo/layouts/shortcodes && cp -r layouts/shortcodes/* themes/congo/layouts/shortcodes/ && cp -r layouts/partials/* themes/congo/layouts/partials/ && hugo --gc --minify -v"

[build.environment]
  HUGO_VERSION = "0.121.0"

[context.production.environment]
  HUGO_ENV = "production"

# Handle form submissions
[dev]
  framework = "#custom"
  command = "hugo server -D"
  targetPort = 1313
